services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    image: ghcr.io/boudabass/elsass-dico:latest
    container_name: next-boilerplate
    ports:
      - "3000:3000"
    volumes:
      # VOLUME PERSISTANT UNIQUE POUR LES DONNÉES (db.json et fichiers uploadés)
      - ./data/storage:/app/data/storage

    environment:
      NODE_ENV: production
      # Les variables Supabase doivent être définies dans l'UI Dyad ou le .env
    env_file:
      - .env

    restart: unless-stopped