-- ============================================
-- Les 390 anomalies de source de culture_alsace, matérialisées (07/09/2026)
-- ============================================
-- CLAUDE.md, campagne 3 : « 390 coquilles de source copiées verbatim et
-- signalées, jamais corrigées (règle 1) », et plus loin « liste finie : elles ne
-- partent jamais dans un lot de publication ».
--
-- Cette liste n'existait nulle part. Ni dans le JSONL (aucun champ de
-- signalement), ni dans le dépôt : elle n'a vécu que dans le rapport d'une carte
-- Hermes, perdu. « Elles ne partent jamais dans un lot » était donc une
-- intention que rien n'appliquait — on ne peut pas exclure ce qu'on ne sait pas
-- nommer.
--
-- Reconstituée le 07/09/2026 en rejouant le parseur du studio
-- (scripts/extract/culture_alsace/lexique_a_d.py, branche data) sur les 73 pages
-- brutes archivées. Contrôles :
--   * le JSONL régénéré est identique octet à octet à celui du dépôt (23 851
--     lignes, même md5 une fois les fins de ligne normalisées) — le rapport
--     décrit donc bien les données réellement en base ;
--   * les 390 références se rattachent toutes à une attestation existante
--     (390/390, 386 attestations distinctes — quelques lignes portent deux
--     anomalies) ;
--   * aucune ne concerne une attestation déjà publiée dans une entrée.
--
-- Le rapport imprimé par le parseur PLAFONNE À 80 anomalies (« … et N autres »).
-- La liste complète a donc été prise en important le module et en rappelant
-- parse_page() page par page, jamais en lisant sa sortie — un plafond
-- d'affichage lu comme un total aurait donné 80 coquilles au lieu de 390.
--
-- Trois types, de gravité inégale :
--   * separateur_tete_non_standard (323) — le « .- » qui sépare la tête de
--     l'équivalent manque ou est coquillé. Le français et l'alsacien extraits
--     restent le plus souvent justes : c'est un signal de parsing.
--   * parenthese_non_fermee (37) — « (la » sans fermeture, qui affecte le
--     contexte.
--   * alsacien_finissant_par_separateur (30) — le plus grave : la forme
--     alsacienne elle-même porte un « .- » parasite (« d'Schofgarwe.- »).
--
-- Rien n'est corrigé ici (règle 1) : la table SIGNALE, elle ne réécrit pas.

CREATE TABLE IF NOT EXISTS public.anomalies_source (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reference TEXT NOT NULL,
  type TEXT NOT NULL,
  detail TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (reference, type)
);

COMMENT ON TABLE public.anomalies_source IS
  'Défauts observés dans une source et copiés verbatim (règle 1) : la table les signale à l''arbitre, elle ne corrige rien. Clé de rattachement : attestations.reference. Reconstituée en rejouant le parseur du studio, jamais saisie à la main.';

CREATE INDEX IF NOT EXISTS ix_anomalies_source_reference
  ON public.anomalies_source (reference);

ALTER TABLE public.anomalies_source ENABLE ROW LEVEL SECURITY;

-- Même régime que attestations : le brut ne sort pas pour un visiteur.
DROP POLICY IF EXISTS anomalies_source_lecture_admin ON public.anomalies_source;
CREATE POLICY anomalies_source_lecture_admin ON public.anomalies_source
  FOR SELECT TO authenticated
  USING (public.is_admin());

-- Idempotent : rejouer la migration ne duplique rien et ne perd rien.
INSERT INTO public.anomalies_source (reference, type, detail) VALUES
  ($a$page_af.htm#L211$a$, $a$separateur_tete_non_standard$a$, $a$tête « absorbé » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L241$a$, $a$separateur_tete_non_standard$a$, $a$tête « accéder » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L292$a$, $a$separateur_tete_non_standard$a$, $a$tête « accouchée. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L341$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« d'Schoofgàrwa, d'Schofgarwe.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_af.htm#L541$a$, $a$separateur_tete_non_standard$a$, $a$tête « affectionner » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L552$a$, $a$separateur_tete_non_standard$a$, $a$tête « affinité » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L566$a$, $a$separateur_tete_non_standard$a$, $a$tête « affolant. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L661$a$, $a$separateur_tete_non_standard$a$, $a$tête « agressif. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L689$a$, $a$separateur_tete_non_standard$a$, $a$tête « aide sociale. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L724$a$, $a$separateur_tete_non_standard$a$, $a$tête « ailette- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L907$a$, $a$separateur_tete_non_standard$a$, $a$tête « altimètre. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1104$a$, $a$separateur_tete_non_standard$a$, $a$tête « année à l'autre. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1171$a$, $a$separateur_tete_non_standard$a$, $a$tête « antimontelait. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1184$a$, $a$separateur_tete_non_standard$a$, $a$tête « antisémite. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1274$a$, $a$separateur_tete_non_standard$a$, $a$tête « appendicite. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1298$a$, $a$separateur_tete_non_standard$a$, $a$tête « appréhension- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1356$a$, $a$separateur_tete_non_standard$a$, $a$tête « arbre généalogique. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1446$a$, $a$separateur_tete_non_standard$a$, $a$tête « arobase. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1474$a$, $a$separateur_tete_non_standard$a$, $a$tête « arrèts. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1481$a$, $a$separateur_tete_non_standard$a$, $a$tête « arrière-goût. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1484$a$, $a$separateur_tete_non_standard$a$, $a$tête « arrière-pensée. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1490$a$, $a$separateur_tete_non_standard$a$, $a$tête « arrivé. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1535$a$, $a$separateur_tete_non_standard$a$, $a$tête « artiste-peintre. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1628$a$, $a$separateur_tete_non_standard$a$, $a$tête « assortiment. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1647$a$, $a$separateur_tete_non_standard$a$, $a$tête « assurance-vieillesse. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_af.htm#L1705$a$, $a$separateur_tete_non_standard$a$, $a$tête « attelé- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L139$a$, $a$parenthèse_non_fermée$a$, $a$« (la » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_bf.htm#L251$a$, $a$separateur_tete_non_standard$a$, $a$tête « banc de sable. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L266$a$, $a$parenthèse_non_fermée$a$, $a$« (la » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_bf.htm#L311$a$, $a$separateur_tete_non_standard$a$, $a$tête « barbouillage. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L355$a$, $a$separateur_tete_non_standard$a$, $a$tête « bas de laine » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L370$a$, $a$separateur_tete_non_standard$a$, $a$tête « Bas-Rhin- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L419$a$, $a$separateur_tete_non_standard$a$, $a$tête « bateleur. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L490$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« vill meh.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_bf.htm#L699$a$, $a$separateur_tete_non_standard$a$, $a$tête « bijou de fantaisie. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L709$a$, $a$parenthèse_non_fermée$a$, $a$« (la » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_bf.htm#L855$a$, $a$separateur_tete_non_standard$a$, $a$tête « boîte à lait. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L868$a$, $a$separateur_tete_non_standard$a$, $a$tête « boîte de petits fours. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L900$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_bf.htm#L933$a$, $a$parenthèse_non_fermée$a$, $a$« (la » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_bf.htm#L966$a$, $a$separateur_tete_non_standard$a$, $a$tête « borner » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L989$a$, $a$separateur_tete_non_standard$a$, $a$tête « bouche de métro. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L1026$a$, $a$separateur_tete_non_standard$a$, $a$tête « bougé- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L1090$a$, $a$separateur_tete_non_standard$a$, $a$tête « bouquet des mariés. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L1155$a$, $a$separateur_tete_non_standard$a$, $a$tête « bouteille non consignée- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L1300$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« bruch.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_bf.htm#L1309$a$, $a$separateur_tete_non_standard$a$, $a$tête « brise-motte. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L1316$a$, $a$separateur_tete_non_standard$a$, $a$tête « brocart. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_bf.htm#L1316$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_bf.htm#L1334$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« berschta, birschte, üssberschta.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_bf.htm#L1365$a$, $a$separateur_tete_non_standard$a$, $a$tête « bruit d'enfer. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L137$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_cf.htm#L233$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_cf.htm#L307$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_cf.htm#L316$a$, $a$separateur_tete_non_standard$a$, $a$tête « camouflage. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L431$a$, $a$separateur_tete_non_standard$a$, $a$tête « capitulation- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L533$a$, $a$separateur_tete_non_standard$a$, $a$tête « carré de lin. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L559$a$, $a$separateur_tete_non_standard$a$, $a$tête « carte de félicitations. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L582$a$, $a$separateur_tete_non_standard$a$, $a$tête « cartonner. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L621$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_cf.htm#L747$a$, $a$separateur_tete_non_standard$a$, $a$tête « celui-là. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L779$a$, $a$separateur_tete_non_standard$a$, $a$tête « centrale nucléaire. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L787$a$, $a$separateur_tete_non_standard$a$, $a$tête « centre d'études. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L916$a$, $a$separateur_tete_non_standard$a$, $a$tête « chambre de torure. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1009$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« d'r Hüatmàcher.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_cf.htm#L1055$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_cf.htm#L1108$a$, $a$separateur_tete_non_standard$a$, $a$tête « chasseur de décorations. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1123$a$, $a$separateur_tete_non_standard$a$, $a$tête « chat domestique. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1155$a$, $a$separateur_tete_non_standard$a$, $a$tête « chauffe-assiettes. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1195$a$, $a$separateur_tete_non_standard$a$, $a$tête « chef-lieu. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1315$a$, $a$separateur_tete_non_standard$a$, $a$tête « chien policier. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1391$a$, $a$separateur_tete_non_standard$a$, $a$tête « chou-rouge. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1410$a$, $a$separateur_tete_non_standard$a$, $a$tête « christianisme. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1481$a$, $a$separateur_tete_non_standard$a$, $a$tête « cintrer » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1548$a$, $a$separateur_tete_non_standard$a$, $a$tête « claie de pressoir. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1610$a$, $a$separateur_tete_non_standard$a$, $a$tête « clé de voiture. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1628$a$, $a$separateur_tete_non_standard$a$, $a$tête « climatiseur. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1639$a$, $a$separateur_tete_non_standard$a$, $a$tête « cloche à fromages. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1646$a$, $a$separateur_tete_non_standard$a$, $a$tête « cloîtrer. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1718$a$, $a$separateur_tete_non_standard$a$, $a$tête « coeur. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1750$a$, $a$separateur_tete_non_standard$a$, $a$tête « coiffe à noeud. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1811$a$, $a$separateur_tete_non_standard$a$, $a$tête « collier d'attelage. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1854$a$, $a$separateur_tete_non_standard$a$, $a$tête « colvert. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1874$a$, $a$separateur_tete_non_standard$a$, $a$tête « comble. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L1887$a$, $a$separateur_tete_non_standard$a$, $a$tête « comité de lecture. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2007$a$, $a$separateur_tete_non_standard$a$, $a$tête « comprenette difficile. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2023$a$, $a$separateur_tete_non_standard$a$, $a$tête « compte courant. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2025$a$, $a$separateur_tete_non_standard$a$, $a$tête « compte épargne logement. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2034$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_cf.htm#L2088$a$, $a$separateur_tete_non_standard$a$, $a$tête « condensé. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2098$a$, $a$separateur_tete_non_standard$a$, $a$tête « conductibilité » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2112$a$, $a$separateur_tete_non_standard$a$, $a$tête « conférence à trois. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2289$a$, $a$separateur_tete_non_standard$a$, $a$tête « conte de noêl. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2351$a$, $a$separateur_tete_non_standard$a$, $a$tête « contre-courant. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2357$a$, $a$separateur_tete_non_standard$a$, $a$tête « contre-exemple. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2374$a$, $a$separateur_tete_non_standard$a$, $a$tête « contre-poison. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2438$a$, $a$separateur_tete_non_standard$a$, $a$tête « copulation. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2523$a$, $a$separateur_tete_non_standard$a$, $a$tête « corps législatif. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2537$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_cf.htm#L2563$a$, $a$separateur_tete_non_standard$a$, $a$tête « costume croisé. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2566$a$, $a$separateur_tete_non_standard$a$, $a$tête « costume régional. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2650$a$, $a$separateur_tete_non_standard$a$, $a$tête « coup du sort. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2682$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_cf.htm#L2694$a$, $a$separateur_tete_non_standard$a$, $a$tête « courant d'eau. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2723$a$, $a$separateur_tete_non_standard$a$, $a$tête « couronne mortuaire. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2723$a$, $a$parenthèse_non_fermée$a$, $a$« (la » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_cf.htm#L2784$a$, $a$separateur_tete_non_standard$a$, $a$tête « couturier. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2792$a$, $a$separateur_tete_non_standard$a$, $a$tête « couvert d'argent. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2811$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_cf.htm#L2868$a$, $a$separateur_tete_non_standard$a$, $a$tête « crème d'avoine. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_cf.htm#L2892$a$, $a$parenthèse_non_fermée$a$, $a$« (les » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_cf.htm#L2982$a$, $a$separateur_tete_non_standard$a$, $a$tête « crotte de chien. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L112$a$, $a$separateur_tete_non_standard$a$, $a$tête « dada.-- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L305$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« d'äntschliassung, d'Äntschleesung, d'r Äntschluss.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_df.htm#L321$a$, $a$separateur_tete_non_standard$a$, $a$tête « déclaration de succession. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L480$a$, $a$separateur_tete_non_standard$a$, $a$tête « dégât de toiture. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L482$a$, $a$separateur_tete_non_standard$a$, $a$tête « dégât matériel. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L587$a$, $a$separateur_tete_non_standard$a$, $a$tête « demain après-midi. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L616$a$, $a$separateur_tete_non_standard$a$, $a$tête « démenti. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L646$a$, $a$separateur_tete_non_standard$a$, $a$tête « demoiselle d'honneur. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L721$a$, $a$separateur_tete_non_standard$a$, $a$tête « dépendant. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L774$a$, $a$parenthèse_non_fermée$a$, $a$« (la » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_df.htm#L790$a$, $a$separateur_tete_non_standard$a$, $a$tête « dérangé. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L846$a$, $a$separateur_tete_non_standard$a$, $a$tête « désamorçage. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L853$a$, $a$separateur_tete_non_standard$a$, $a$tête « désarticuler. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L875$a$, $a$separateur_tete_non_standard$a$, $a$tête « désembuer. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L897$a$, $a$separateur_tete_non_standard$a$, $a$tête « déshonorer- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L941$a$, $a$separateur_tete_non_standard$a$, $a$tête « dessouder. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L1125$a$, $a$separateur_tete_non_standard$a$, $a$tête « différemment. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L1252$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_df.htm#L1286$a$, $a$separateur_tete_non_standard$a$, $a$tête « distribution d'eau. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L1354$a$, $a$separateur_tete_non_standard$a$, $a$tête « dommages et intérêts. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L1400$a$, $a$separateur_tete_non_standard$a$, $a$tête « double-porte. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L1439$a$, $a$separateur_tete_non_standard$a$, $a$tête « dragueur de mines. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L1454$a$, $a$separateur_tete_non_standard$a$, $a$tête « droit- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L1458$a$, $a$separateur_tete_non_standard$a$, $a$tête « droit d'auteur. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L1465$a$, $a$separateur_tete_non_standard$a$, $a$tête « droit coutumier. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L1466$a$, $a$separateur_tete_non_standard$a$, $a$tête « droit électoral. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_df.htm#L1492$a$, $a$separateur_tete_non_standard$a$, $a$tête « durée. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L158$a$, $a$separateur_tete_non_standard$a$, $a$tête « ébulition. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L187$a$, $a$separateur_tete_non_standard$a$, $a$tête « écharper » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L227$a$, $a$separateur_tete_non_standard$a$, $a$tête « éclairagiste. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L229$a$, $a$separateur_tete_non_standard$a$, $a$tête « éclaircir- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L246$a$, $a$separateur_tete_non_standard$a$, $a$tête « école d'art et d'industrie. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L252$a$, $a$separateur_tete_non_standard$a$, $a$tête « école libre. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L272$a$, $a$separateur_tete_non_standard$a$, $a$tête « écorce terrestre. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L309$a$, $a$separateur_tete_non_standard$a$, $a$tête « écrire à la main. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L499$a$, $a$separateur_tete_non_standard$a$, $a$tête « embarras gastrique,- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L546$a$, $a$separateur_tete_non_standard$a$, $a$tête « émettre un gaz,- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L658$a$, $a$separateur_tete_non_standard$a$, $a$tête « enchaîner. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L871$a$, $a$separateur_tete_non_standard$a$, $a$tête « entailler._ » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L918$a$, $a$separateur_tete_non_standard$a$, $a$tête « entre autres. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L995$a$, $a$parenthèse_non_fermée$a$, $a$« (d'r » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_ef.htm#L1057$a$, $a$separateur_tete_non_standard$a$, $a$tête « épineux- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L1260$a$, $a$separateur_tete_non_standard$a$, $a$tête « essuie-meuble. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L1264$a$, $a$separateur_tete_non_standard$a$, $a$tête « essuyer les pertes. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L1316$a$, $a$parenthèse_non_fermée$a$, $a$« (non » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_ef.htm#L1422$a$, $a$separateur_tete_non_standard$a$, $a$tête « étroitesse d'esprit. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L1429$a$, $a$separateur_tete_non_standard$a$, $a$tête « étui à lunettes. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L1558$a$, $a$separateur_tete_non_standard$a$, $a$tête « exploitation agricole. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ef.htm#L1559$a$, $a$separateur_tete_non_standard$a$, $a$tête « exploitation forestière. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L106$a$, $a$separateur_tete_non_standard$a$, $a$tête « fabricant de bretzels. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L119$a$, $a$separateur_tete_non_standard$a$, $a$tête « facéties » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L154$a$, $a$separateur_tete_non_standard$a$, $a$tête « fagot de sarments. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L197$a$, $a$separateur_tete_non_standard$a$, $a$tête « faire des calins » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L261$a$, $a$separateur_tete_non_standard$a$, $a$tête « faire un café. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L264$a$, $a$separateur_tete_non_standard$a$, $a$tête « faire une demande. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L367$a$, $a$parenthèse_non_fermée$a$, $a$« (les » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_ff.htm#L455$a$, $a$separateur_tete_non_standard$a$, $a$tête « le faux-jeton. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L506$a$, $a$separateur_tete_non_standard$a$, $a$tête « fendeur de bois. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L526$a$, $a$separateur_tete_non_standard$a$, $a$tête « fer à souder. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L628$a$, $a$parenthèse_non_fermée$a$, $a$« (les » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_ff.htm#L658$a$, $a$separateur_tete_non_standard$a$, $a$tête « fiche de vaccination. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L715$a$, $a$separateur_tete_non_standard$a$, $a$tête « fil de raccordement. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L774$a$, $a$separateur_tete_non_standard$a$, $a$tête « financier » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L775$a$, $a$separateur_tete_non_standard$a$, $a$tête « financier » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L811$a$, $a$separateur_tete_non_standard$a$, $a$tête « fixer des yeux. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L896$a$, $a$separateur_tete_non_standard$a$, $a$tête « flocon de neige. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L995$a$, $a$separateur_tete_non_standard$a$, $a$tête « fond de terre. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L999$a$, $a$separateur_tete_non_standard$a$, $a$tête « fondé de pouvoir. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L1000$a$, $a$separateur_tete_non_standard$a$, $a$tête « fondement. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L1066$a$, $a$separateur_tete_non_standard$a$, $a$tête « formater. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L1070$a$, $a$separateur_tete_non_standard$a$, $a$tête « formation des adultes. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L1073$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« d'r Modl.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_ff.htm#L1081$a$, $a$separateur_tete_non_standard$a$, $a$tête « formulaire de déclaration. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L1087$a$, $a$separateur_tete_non_standard$a$, $a$tête « formulette. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L1166$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_ff.htm#L1397$a$, $a$separateur_tete_non_standard$a$, $a$tête « front de taille. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_ff.htm#L1419$a$, $a$parenthèse_non_fermée$a$, $a$« (les » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_gf.htm#L158$a$, $a$separateur_tete_non_standard$a$, $a$tête « galerie d'écoulement. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L200$a$, $a$separateur_tete_non_standard$a$, $a$tête « gant de velours. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L213$a$, $a$separateur_tete_non_standard$a$, $a$tête « garçon mal coiffé. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L255$a$, $a$parenthèse_non_fermée$a$, $a$« (la » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_gf.htm#L292$a$, $a$separateur_tete_non_standard$a$, $a$tête « gâteau roulé aux fruits secs. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L416$a$, $a$separateur_tete_non_standard$a$, $a$tête « gens d'affaires » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L419$a$, $a$separateur_tete_non_standard$a$, $a$tête « gens de lettres. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L419$a$, $a$parenthèse_non_fermée$a$, $a$« (les » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_gf.htm#L429$a$, $a$separateur_tete_non_standard$a$, $a$tête « gentilhomme. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L559$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« uff'm Glànzgepfel.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_gf.htm#L611$a$, $a$separateur_tete_non_standard$a$, $a$tête « gonfleur.' » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L665$a$, $a$separateur_tete_non_standard$a$, $a$tête « gousse de vanille. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L764$a$, $a$separateur_tete_non_standard$a$, $a$tête « graisseux. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L778$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« sehr.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_gf.htm#L788$a$, $a$separateur_tete_non_standard$a$, $a$tête « grandir. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L791$a$, $a$separateur_tete_non_standard$a$, $a$tête « grand dormeur. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L810$a$, $a$separateur_tete_non_standard$a$, $a$tête « grand-route. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L860$a$, $a$separateur_tete_non_standard$a$, $a$tête « gratter la terre. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L863$a$, $a$separateur_tete_non_standard$a$, $a$tête « gratuité de l'enseignement. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L912$a$, $a$separateur_tete_non_standard$a$, $a$tête « grève de la faim. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L964$a$, $a$separateur_tete_non_standard$a$, $a$tête « grisonner. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L964$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« gràui wara.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_gf.htm#L1049$a$, $a$separateur_tete_non_standard$a$, $a$tête « guérir en dormant. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_gf.htm#L1078$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_hf.htm#L274$a$, $a$separateur_tete_non_standard$a$, $a$tête « héréditaire;- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_hf.htm#L336$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« s'Glachters.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_hf.htm#L411$a$, $a$separateur_tete_non_standard$a$, $a$tête « horloge de la gare. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_hf.htm#L428$a$, $a$separateur_tete_non_standard$a$, $a$tête « hors de propos. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_hf.htm#L457$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« d'Hohldeela.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_hf.htm#L498$a$, $a$separateur_tete_non_standard$a$, $a$tête « humidité de l'air. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_hf.htm#L519$a$, $a$separateur_tete_non_standard$a$, $a$tête « hydrogène- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_if.htm#L104$a$, $a$separateur_tete_non_standard$a$, $a$tête « ici peu. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_if.htm#L114$a$, $a$separateur_tete_non_standard$a$, $a$tête « idées noires. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_if.htm#L279$a$, $a$separateur_tete_non_standard$a$, $a$tête « impôts sur le salaire. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_if.htm#L327$a$, $a$separateur_tete_non_standard$a$, $a$tête « inassimilable. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_if.htm#L375$a$, $a$separateur_tete_non_standard$a$, $a$tête « incommodant. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_if.htm#L505$a$, $a$separateur_tete_non_standard$a$, $a$tête « induire en erreur. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_if.htm#L509$a$, $a$separateur_tete_non_standard$a$, $a$tête « induration. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_if.htm#L746$a$, $a$separateur_tete_non_standard$a$, $a$tête « instrument de musique. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_if.htm#L853$a$, $a$separateur_tete_non_standard$a$, $a$tête « intouchable. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_if.htm#L865$a$, $a$separateur_tete_non_standard$a$, $a$tête « introduire en fraude. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_jf.htm#L121$a$, $a$separateur_tete_non_standard$a$, $a$tête « jamais » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_jf.htm#L212$a$, $a$separateur_tete_non_standard$a$, $a$tête « jeu d'échecs. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_jf.htm#L237$a$, $a$separateur_tete_non_standard$a$, $a$tête « joie de vivre/- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_jf.htm#L312$a$, $a$separateur_tete_non_standard$a$, $a$tête « joute oratoire. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_jf.htm#L338$a$, $a$separateur_tete_non_standard$a$, $a$tête « jugeotte. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L143$a$, $a$separateur_tete_non_standard$a$, $a$tête « laine » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L191$a$, $a$separateur_tete_non_standard$a$, $a$tête « lamier blanc. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L197$a$, $a$separateur_tete_non_standard$a$, $a$tête « lampe à néon. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L213$a$, $a$separateur_tete_non_standard$a$, $a$tête « lance-roquette. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L218$a$, $a$separateur_tete_non_standard$a$, $a$tête « lancer du marteau. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L248$a$, $a$separateur_tete_non_standard$a$, $a$tête « lapereau. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L354$a$, $a$separateur_tete_non_standard$a$, $a$tête « légitime défense. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L409$a$, $a$separateur_tete_non_standard$a$, $a$tête « lever de lune. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L415$a$, $a$separateur_tete_non_standard$a$, $a$tête « lever les yeux. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L442$a$, $a$separateur_tete_non_standard$a$, $a$tête « liberté d'esprit. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L446$a$, $a$separateur_tete_non_standard$a$, $a$tête « liberté d'expression. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L451$a$, $a$separateur_tete_non_standard$a$, $a$tête « libre. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L524$a$, $a$separateur_tete_non_standard$a$, $a$tête « limitation des naissances. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L526$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« d'Granza, d'Schranka.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_lf.htm#L563$a$, $a$separateur_tete_non_standard$a$, $a$tête « lire dans la main. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L649$a$, $a$separateur_tete_non_standard$a$, $a$tête « loger une balle dans la tète. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L709$a$, $a$separateur_tete_non_standard$a$, $a$tête « lot de consolation. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_lf.htm#L724$a$, $a$separateur_tete_non_standard$a$, $a$tête « loup de mer. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L165$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« verhärrliga.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_mf.htm#L184$a$, $a$separateur_tete_non_standard$a$, $a$tête « main d'oeuvre. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L239$a$, $a$separateur_tete_non_standard$a$, $a$tête « maîtriser._ » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L273$a$, $a$separateur_tete_non_standard$a$, $a$tête « mal de cheveux. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L362$a$, $a$separateur_tete_non_standard$a$, $a$tête « manger de la vache enragé. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L398$a$, $a$separateur_tete_non_standard$a$, $a$tête « manouche. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L406$a$, $a$separateur_tete_non_standard$a$, $a$tête « manque d'intérèt. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L469$a$, $a$separateur_tete_non_standard$a$, $a$tête « marche des affaires. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L487$a$, $a$separateur_tete_non_standard$a$, $a$tête « marcher derrière. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L514$a$, $a$separateur_tete_non_standard$a$, $a$tête « mariage de raison. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L522$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« ileega, ibaitza, schmoora, sech làngwihla.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_mf.htm#L713$a$, $a$separateur_tete_non_standard$a$, $a$tête « mécanicien de précision. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L735$a$, $a$separateur_tete_non_standard$a$, $a$tête « médecin d'urgence. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L741$a$, $a$separateur_tete_non_standard$a$, $a$tête « médecine douce. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L772$a$, $a$separateur_tete_non_standard$a$, $a$tête « meilleurs remerciements. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L924$a$, $a$parenthèse_non_fermée$a$, $a$« (les » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_mf.htm#L926$a$, $a$separateur_tete_non_standard$a$, $a$tête « messe de minuit- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L976$a$, $a$separateur_tete_non_standard$a$, $a$tête « mètre pliant. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L1091$a$, $a$separateur_tete_non_standard$a$, $a$tête « mince alors!- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L1095$a$, $a$parenthèse_non_fermée$a$, $a$« (la » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_mf.htm#L1312$a$, $a$separateur_tete_non_standard$a$, $a$tête « monte en l'air. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L1365$a$, $a$separateur_tete_non_standard$a$, $a$tête « morsure- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_mf.htm#L1404$a$, $a$separateur_tete_non_standard$a$, $a$tête « motion de censure. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_nf.htm#L114$a$, $a$separateur_tete_non_standard$a$, $a$tête « nager dans l'oppulence. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_nf.htm#L229$a$, $a$separateur_tete_non_standard$a$, $a$tête « neige fraîche. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_nf.htm#L252$a$, $a$separateur_tete_non_standard$a$, $a$tête « nettoyeur à haute pression. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_nf.htm#L299$a$, $a$parenthèse_non_fermée$a$, $a$« (les » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_nf.htm#L330$a$, $a$separateur_tete_non_standard$a$, $a$tête « noeud papillon. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_nf.htm#L357$a$, $a$separateur_tete_non_standard$a$, $a$tête « nom propre. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_nf.htm#L384$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« unsenn.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_nf.htm#L431$a$, $a$separateur_tete_non_standard$a$, $a$tête « nouveau-né. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_nf.htm#L435$a$, $a$separateur_tete_non_standard$a$, $a$tête « nouvelle-lune. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_nf.htm#L455$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« schättiara.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_of.htm#L123$a$, $a$separateur_tete_non_standard$a$, $a$tête « obligation militaire. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_of.htm#L129$a$, $a$separateur_tete_non_standard$a$, $a$tête « obligeamment. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_of.htm#L157$a$, $a$separateur_tete_non_standard$a$, $a$tête « observer. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_of.htm#L238$a$, $a$separateur_tete_non_standard$a$, $a$tête « office du logement. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_of.htm#L265$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« d'Weldgàns.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_of.htm#L394$a$, $a$separateur_tete_non_standard$a$, $a$tête « oraison funèbre. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L138$a$, $a$separateur_tete_non_standard$a$, $a$tête « pain béni » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L146$a$, $a$separateur_tete_non_standard$a$, $a$tête « pain de sucre- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L176$a$, $a$separateur_tete_non_standard$a$, $a$tête « palfrenier. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L230$a$, $a$separateur_tete_non_standard$a$, $a$tête « panier à linge. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L231$a$, $a$separateur_tete_non_standard$a$, $a$tête « panier à ouvrages. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L349$a$, $a$separateur_tete_non_standard$a$, $a$tête « parc à huitres. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L350$a$, $a$separateur_tete_non_standard$a$, $a$tête « parc d'attraction. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L351$a$, $a$separateur_tete_non_standard$a$, $a$tête « parc de bébé » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L364$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« em gegasàtz.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_pf.htm#L382$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« gwàffnet.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_pf.htm#L458$a$, $a$separateur_tete_non_standard$a$, $a$tête « par tas. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L636$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« biasa.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_pf.htm#L643$a$, $a$separateur_tete_non_standard$a$, $a$tête « patrimoine culturel. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L694$a$, $a$separateur_tete_non_standard$a$, $a$tête « pays d'origine. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L736$a$, $a$separateur_tete_non_standard$a$, $a$tête « pédalier. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L776$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« scheela.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_pf.htm#L831$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« danka.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_pf.htm#L838$a$, $a$separateur_tete_non_standard$a$, $a$tête « pension de veuve. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L1075$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« d'klaina Littla.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_pf.htm#L1131$a$, $a$separateur_tete_non_standard$a$, $a$tête « pharingite. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L1183$a$, $a$separateur_tete_non_standard$a$, $a$tête « pic épeiche. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L1227$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_pf.htm#L1300$a$, $a$separateur_tete_non_standard$a$, $a$tête « pin parasol. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L1309$a$, $a$separateur_tete_non_standard$a$, $a$tête « pince à cheveux. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L1537$a$, $a$separateur_tete_non_standard$a$, $a$tête « plein à craquer. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L1705$a$, $a$separateur_tete_non_standard$a$, $a$tête « point d'interrogation. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L1763$a$, $a$separateur_tete_non_standard$a$, $a$tête « polaire. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L1901$a$, $a$separateur_tete_non_standard$a$, $a$tête « porte flambeau. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L1993$a$, $a$separateur_tete_non_standard$a$, $a$tête « pot au feu._ » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L2137$a$, $a$separateur_tete_non_standard$a$, $a$tête « précieusement. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L2311$a$, $a$separateur_tete_non_standard$a$, $a$tête « prêter l'oreille. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_pf.htm#L2566$a$, $a$separateur_tete_non_standard$a$, $a$tête « protection de la nature. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_qf.htm#L209$a$, $a$separateur_tete_non_standard$a$, $a$tête « qui pis est. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_qf.htm#L213$a$, $a$separateur_tete_non_standard$a$, $a$tête « qui va là. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_rf.htm#L260$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« s'chtagaglander.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_rf.htm#L470$a$, $a$separateur_tete_non_standard$a$, $a$tête « recevoir en retour. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_rf.htm#L520$a$, $a$separateur_tete_non_standard$a$, $a$tête « reconnaissance de dette. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_rf.htm#L580$a$, $a$separateur_tete_non_standard$a$, $a$tête « rédemption. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_rf.htm#L603$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_rf.htm#L609$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« s'Kammerla.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_rf.htm#L701$a$, $a$separateur_tete_non_standard$a$, $a$tête « région lombaire. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_rf.htm#L855$a$, $a$separateur_tete_non_standard$a$, $a$tête « remettre au pas. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_rf.htm#L927$a$, $a$separateur_tete_non_standard$a$, $a$tête « rendre inquièt. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_rf.htm#L1166$a$, $a$separateur_tete_non_standard$a$, $a$tête « ressources personnelles. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_rf.htm#L1248$a$, $a$separateur_tete_non_standard$a$, $a$tête « rétrécissement. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_rf.htm#L1284$a$, $a$separateur_tete_non_standard$a$, $a$tête « réveillon de Noël. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_rf.htm#L1310$a$, $a$separateur_tete_non_standard$a$, $a$tête « reverser. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_rf.htm#L1314$a$, $a$separateur_tete_non_standard$a$, $a$tête « rêveur. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_rf.htm#L1479$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« s'Liawesliad.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_rf.htm#L1563$a$, $a$separateur_tete_non_standard$a$, $a$tête « rouge d'andrinople. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L151$a$, $a$separateur_tete_non_standard$a$, $a$tête « sacré somme. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L257$a$, $a$separateur_tete_non_standard$a$, $a$tête « salle de conférence. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L392$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« d'r Wàld un Barggaischt, d'r Sittaschtrolch.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_sf.htm#L724$a$, $a$separateur_tete_non_standard$a$, $a$tête « sentir le vent venir. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L765$a$, $a$separateur_tete_non_standard$a$, $a$tête « serment de fidélité. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L834$a$, $a$separateur_tete_non_standard$a$, $a$tête « seuil de l'hiver. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L852$a$, $a$separateur_tete_non_standard$a$, $a$tête « shampoing » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L886$a$, $a$separateur_tete_non_standard$a$, $a$tête « signature du contrat. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L890$a$, $a$separateur_tete_non_standard$a$, $a$tête « signe de décadence. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L945$a$, $a$separateur_tete_non_standard$a$, $a$tête « sinusite maxilaire. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L957$a$, $a$separateur_tete_non_standard$a$, $a$tête « site classé » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L958$a$, $a$separateur_tete_non_standard$a$, $a$tête « site protégé. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L1062$a$, $a$parenthèse_non_fermée$a$, $a$« (les » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_sf.htm#L1138$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« d'Klàngfàrb.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_sf.htm#L1193$a$, $a$separateur_tete_non_standard$a$, $a$tête « soufflé. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L1204$a$, $a$separateur_tete_non_standard$a$, $a$tête « souffreuteux. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L1232$a$, $a$separateur_tete_non_standard$a$, $a$tête « soupe à l'oignon. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L1235$a$, $a$separateur_tete_non_standard$a$, $a$tête « soupe de légumes. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L1267$a$, $a$separateur_tete_non_standard$a$, $a$tête « sous-bois- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L1367$a$, $a$parenthèse_non_fermée$a$, $a$« (le » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_sf.htm#L1385$a$, $a$separateur_tete_non_standard$a$, $a$tête « station balnéaire. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L1390$a$, $a$separateur_tete_non_standard$a$, $a$tête « station de métro. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L1395$a$, $a$separateur_tete_non_standard$a$, $a$tête « station thermale. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L1478$a$, $a$separateur_tete_non_standard$a$, $a$tête « submersible. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_sf.htm#L1640$a$, $a$separateur_tete_non_standard$a$, $a$tête « surpeuplé. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_tf.htm#L172$a$, $a$separateur_tete_non_standard$a$, $a$tête « tailler une bavette. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_tf.htm#L195$a$, $a$separateur_tete_non_standard$a$, $a$tête « tambour-major. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_tf.htm#L435$a$, $a$separateur_tete_non_standard$a$, $a$tête « tenancier. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_tf.htm#L663$a$, $a$separateur_tete_non_standard$a$, $a$tête « tir au pigeon. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_tf.htm#L665$a$, $a$separateur_tete_non_standard$a$, $a$tête « tir de sommation.( » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_tf.htm#L678$a$, $a$separateur_tete_non_standard$a$, $a$tête « tiré à quatre épingles. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_tf.htm#L884$a$, $a$separateur_tete_non_standard$a$, $a$tête « toujours et encore. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_tf.htm#L943$a$, $a$separateur_tete_non_standard$a$, $a$tête « tourner le dos. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_tf.htm#L972$a$, $a$separateur_tete_non_standard$a$, $a$tête « tout à l'égout. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_tf.htm#L988$a$, $a$separateur_tete_non_standard$a$, $a$tête « tout pour le tout. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_tf.htm#L1041$a$, $a$separateur_tete_non_standard$a$, $a$tête « trahison » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_tf.htm#L1116$a$, $a$parenthèse_non_fermée$a$, $a$« (la » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_tf.htm#L1325$a$, $a$separateur_tete_non_standard$a$, $a$tête « trippler. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_tf.htm#L1360$a$, $a$parenthèse_non_fermée$a$, $a$« (les » — parenthèse non fermée dans la source (copiée verbatim)$a$),
  ($a$page_tf.htm#L1403$a$, $a$separateur_tete_non_standard$a$, $a$tête « trouble carrentiel. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_tf.htm#L1428$a$, $a$alsacien_finissant_par_séparateur$a$, $a$« sech wohl fühla.- » — « .- » final dans l'alsacien (coquille, copiée verbatim)$a$),
  ($a$page_tf.htm#L1470$a$, $a$separateur_tete_non_standard$a$, $a$tête « tumeur cancéreuse. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_uf.htm#L150$a$, $a$separateur_tete_non_standard$a$, $a$tête « urbaniser._ » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_vf.htm#L299$a$, $a$separateur_tete_non_standard$a$, $a$tête « venir à la maison. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_vf.htm#L333$a$, $a$separateur_tete_non_standard$a$, $a$tête « vers- » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_vf.htm#L578$a$, $a$separateur_tete_non_standard$a$, $a$tête « violation de sépulture. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_vf.htm#L601$a$, $a$separateur_tete_non_standard$a$, $a$tête « virage à gauche. » — séparateur absent ou coquille (copié, non corrigé)$a$),
  ($a$page_vf.htm#L602$a$, $a$separateur_tete_non_standard$a$, $a$tête « virage en  épingle à cheveux. » — séparateur absent ou coquille (copié, non corrigé)$a$)
ON CONFLICT (reference, type) DO UPDATE SET detail = EXCLUDED.detail;

-- ============================================
-- anomalies_de() : le signalement d'une attestation, prêt à joindre
-- ============================================
-- Appelée depuis candidats_arbitrage() et detail_candidat()
-- (20260907020000) pour poser le signalement dans chaque variante, sans y
-- recopier une sous-requête. NULL quand la référence est saine — l'immense
-- majorité des cas.

CREATE OR REPLACE FUNCTION public.anomalies_de(p_reference TEXT)
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $fn$
  SELECT jsonb_agg(jsonb_build_object('type', a.type, 'detail', a.detail) ORDER BY a.type)
  FROM public.anomalies_source a
  WHERE p_reference IS NOT NULL AND a.reference = p_reference;
$fn$;

COMMENT ON FUNCTION public.anomalies_de(TEXT) IS
  'Anomalies de source rattachées à une attestation, par sa référence, ou NULL. SECURITY DEFINER parce qu''elle est appelée depuis les fonctions d''arbitrage, elles-mêmes réservées aux admins par is_admin() : le brut ne devient pas lisible pour autant.';
