// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lrrrxolpzpnhuavfjezd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxycnJ4b2xwenBuaHVhdmZqZXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxODM5NzYsImV4cCI6MjA4MDc1OTk3Nn0.bTaw1I6_ckl5nATIg2dl7GqUAdYnMpXm0onniBn_CGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);